   /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemonoyunu;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Mustafa
 */
public class PokemonOyunu1 extends javax.swing.JFrame {

    //static int kontrol;
    static int[] kartlarİnsan= new int[5];
    static int[] kartlarBilgisayar= new int[5];
    static String[] konum = new String[50];
    int[] BilgisayarPuan = new int[5];
    int[] İnsanPuan = new int[5];
    static int SonSkorPc=0;
    static int SonSkorİnsan=0;
    static int KartBittiMi=0;
    static int Sayac=0;
    static int[] denemem=new int[5];
    static int [] denemem1=new int [5];

    /**
     * Creates new form PokemonOyunu1
     */
    public PokemonOyunu1() {
        initComponents();
        
    }
    
   
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        insanKart3 = new javax.swing.JButton();
        insanKart1 = new javax.swing.JButton();
        insanKart2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(2000, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox3.setText("insan-pc");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 132, -1));

        jButton2.setText("Kart Çek");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 52, -1, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1237, 180, 200, 270));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1476, 180, 200, 270));

        jTextField1.setText("Oyuncu");
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 60, 110, -1));

        jTextField2.setText("Bilgisayar");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 60, 120, -1));

        insanKart3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insanKart3ActionPerformed(evt);
            }
        });
        jPanel1.add(insanKart3, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 545, 180, 250));

        insanKart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insanKart1ActionPerformed(evt);
            }
        });
        jPanel1.add(insanKart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 545, 180, 250));

        insanKart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insanKart2ActionPerformed(evt);
            }
        });
        jPanel1.add(insanKart2, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 545, 180, 250));

        jTextField3.setForeground(new java.awt.Color(255, 0, 255));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 120, 70, -1));

        jTextField4.setForeground(new java.awt.Color(255, 0, 255));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 120, 67, -1));

        jCheckBox1.setText("Pc-Pc");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 0, -1, -1));

        jButton1.setText("Oyna");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 137, -1, -1));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 56, 160, 220));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 160, 220));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 56, 160, 220));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 56, 160, 220));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 160, 220));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 160, 220));

        jTextField5.setForeground(new java.awt.Color(255, 51, 51));
        jTextField5.setText("Puan Durumu");
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 0, 110, -1));

        jTextField6.setText("Blgisayar1");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 110, -1));

        jTextField7.setText("Bilgisayar");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 350, 110, -1));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 560, 160, 220));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 560, 160, 220));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 560, 160, 220));

        jTextField8.setText("Oyuncu 1");
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 860, 90, -1));

        jTextField9.setText("Bilgisayar");
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 860, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1752, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
   
    
    
    
    
    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
        
        
        List<pokemon> pokemonList = new ArrayList<pokemon>();
        pokemonList = pokemonList();
        int[] sayilar = new int[10];
        sayilar = rand();

        
          
            
            if( jCheckBox3.isSelected() == true )
            {
                
            jCheckBox1.setVisible(false);
            
                
                
                
                

            BilgisayarOyuncusu pc = new BilgisayarOyuncusu();
            pc.setOyuncuID(1);
            pc.setOyuncuAdi("mustafa");
            for (int i = 0; i < 3; i++) {
                pc.kartListesi[i] = sayilar[i];
                System.out.println(pc.kartListesi[i]);

            }
            //  System.out.println(pokemonList.get(pc.kartListesi[0]).getPokemonName() + ", " + pokemonList.get(pc.kartListesi[0]).getPokemonID());

            InsanOyuncusu insan = new InsanOyuncusu();
            insan.setOyuncuID(1);
            insan.setOyuncuAdi("ömer");
            for (int i = 3; i < 6; i++) {
                insan.kartListesi[i-3] = sayilar[i];
                System.out.println(insan.kartListesi[i-3]);

            }
            //int id=pc.kartListesi[0];
            //            System.out.println("id " +id);

            //int hp=pokemonList.get().hasarPuaniGoster();
            //int hp1= pokemonList.get(insan.kartListesi[0]).hasarPuaniGoster();
            int insanSkor=0;
            int pcSkor=0;
            //           System.out.println("hp "+hp);
            //          System.out.println("hp1 "+hp1);
            
        konum[0]="../pokemonOyunu/src/pokemonoyunu/img/pikachu.jpg";
        konum[1]="../pokemonOyunu/src/pokemonoyunu/img/balbasaur.jpg";
        konum[2]="../pokemonOyunu/src/pokemonoyunu/img/Charmander.jpg";
        konum[3]="../pokemonOyunu/src/pokemonoyunu/img/Squirtle.jpg";
        konum[4]="../pokemonOyunu/src/pokemonoyunu/img/Zubat.jpg";
        konum[5]="../pokemonOyunu/src/pokemonoyunu/img/Psyduck.jpg";
        konum[6]="../pokemonOyunu/src/pokemonoyunu/img/Snorlax.jpg";
        konum[7]="../pokemonOyunu/src/pokemonoyunu/img/Butterfree.jpg";
        konum[8]="../pokemonOyunu/src/pokemonoyunu/img/Jigglypuff.jpg";
        konum[9]="../pokemonOyunu/src/pokemonoyunu/img/Meowth.jpg";
        insanKart1.setIcon(new javax.swing.ImageIcon(konum[insan.kartListesi[0]]));
        insanKart2.setIcon(new javax.swing.ImageIcon(konum[insan.kartListesi[1]]));
        insanKart3.setIcon(new javax.swing.ImageIcon(konum[insan.kartListesi[2]]));
        
        jLabel9.setIcon(new javax.swing.ImageIcon(konum[pc.kartListesi[0]]));
        jLabel10.setIcon(new javax.swing.ImageIcon(konum[pc.kartListesi[1]]));
        jLabel11.setIcon(new javax.swing.ImageIcon(konum[pc.kartListesi[2]]));
            
             int tut=0;
            int tut1=0;
            System.arraycopy(pc.kartListesi,0,denemem,0,5); 
            for(int i=0;i<3;i++){
                for(int j=i;j<3;j++){
                    if(pc.kartListesi[i]<pc.kartListesi[i+1]){
                    tut=pc.kartListesi[i];
                    pc.kartListesi[i]=pc.kartListesi[i+1];
                    pc.kartListesi[i+1]=tut;
                    }                    
                }
            }
            
            
            
            

            for(int i=0;i<3;i++)
            {
                System.out.println(pokemonList.get(pc.kartListesi[i]).hasarPuaniGoster()+"    "+pokemonList.get(insan.kartListesi[i]).hasarPuaniGoster());
                if(pokemonList.get(pc.kartListesi[i]).hasarPuaniGoster()>pokemonList.get(insan.kartListesi[i]).hasarPuaniGoster()){
                    //pcSkor=pcSkor+5;
                    pcSkor=5;
                    insanSkor=0;
                    İnsanPuan[i]=insanSkor;
                    BilgisayarPuan[i]=pcSkor;
                    System.out.println("1.puan "+pcSkor);
                    System.out.println("2.puan "+insanSkor);
                  
                }
                else if (pokemonList.get(pc.kartListesi[i]).hasarPuaniGoster()<pokemonList.get(insan.kartListesi[i]).hasarPuaniGoster()){
                    //insanSkor=insanSkor+5;
                    pcSkor=0;
                    insanSkor=5;
                    İnsanPuan[i]=insanSkor;
                    System.out.println("1.puan "+pcSkor);
                    System.out.println("2.puan "+insanSkor);
                    BilgisayarPuan[i]=pcSkor;
                }
                else {
                    insanSkor=insanSkor+0;
                    //pcSkor=pcSkor+0;
                    pcSkor=0;
                    insanSkor=0;
                    İnsanPuan[i]=insanSkor;
                    System.out.println("1.puan "+pcSkor);
                    System.out.println("2.puan "+insanSkor);
                    BilgisayarPuan[i]=pcSkor;

                }
            }
            for(int i=0; i<3 ; i++)
            {
                System.out.println("skorlar denemesi: "+BilgisayarPuan[i]);
            }
            
            
            insan.kartListesi[3]=sayilar[6];
            pc.kartListesi[3]=sayilar[7];
            insan.kartListesi[4]=sayilar[8];
            pc.kartListesi[4]=sayilar[9];
            //insan.kartListesi[4]=sayilar[6];
            // System.out.println(pc.kartListesi[3]);
            //System.out.println(pokemonList.get(pc.kartListesi[3]).hasarPuaniGoster());
            for(int i=3;i<5;i++){
                System.out.println(pokemonList.get(pc.kartListesi[i]).hasarPuaniGoster()+"    "+pokemonList.get(insan.kartListesi[i]).hasarPuaniGoster());
                if(pokemonList.get(pc.kartListesi[i]).hasarPuaniGoster()>pokemonList.get(insan.kartListesi[i]).hasarPuaniGoster()){
                    pcSkor=5;
                    insanSkor=0;
                    İnsanPuan[i]=insanSkor;
                    BilgisayarPuan[i]=pcSkor;
                    
                    System.out.println("1.puan: "+pcSkor);
                    System.out.println("2.puan: "+insanSkor);
                }
                else if(pokemonList.get(pc.kartListesi[i]).hasarPuaniGoster()<pokemonList.get(insan.kartListesi[i]).hasarPuaniGoster()){
                    insanSkor=5;
                    İnsanPuan[i]=insanSkor;
                    pcSkor=0;
                    BilgisayarPuan[i]=pcSkor;
                    System.out.println("1.puan: "+pcSkor);
                    System.out.println("2.puan: "+insanSkor);

                }
                else{
                    pcSkor=0;
                    BilgisayarPuan[i]=pcSkor;
                    insanSkor=0;
                    İnsanPuan[i]=insanSkor;
                    System.out.println("1.puan: "+pcSkor);
                    System.out.println("2.puan: "+insanSkor);

                }

            }
            if(pcSkor>insanSkor){
                System.out.println("1.oyuncu bilgisayaar kazandi");
            }
            else if(insanSkor>pcSkor)
            {
                System.out.println("2.oyuncu insan kazandi");
            }
            else{
                System.out.println("berabere kaldiniz");
            }
            
            

         for(int i=0; i<5 ; i++)
         {
             kartlarİnsan[i]=insan.kartListesi[i];
             kartlarBilgisayar[i]=pc.kartListesi[i];
         }
        
         
            //}
            
            
        
        
        insanKart1.setVisible(true);
        insanKart2.setVisible(true);
        insanKart3.setVisible(true);
        
        jLabel9.setVisible(true);
        jLabel10.setVisible(true);
        jLabel11.setVisible(true);
        
        
        
        //jButton2.setVisible(true);
        SonSkorPc=0;
        jTextField3.setText(Integer.toString(SonSkorPc));
        SonSkorİnsan=0;
        jTextField4.setText(Integer.toString(SonSkorİnsan));
        
        
        jButton2.setVisible(false);
        jButton1.setVisible(false);
        KartBittiMi=0;
        
        insanKart1.setVisible(true);
         insanKart2.setVisible(true);
         insanKart3.setVisible(true);
         
         
         jLabel5.setVisible(false);
         jLabel7.setVisible(false);
         jLabel6.setVisible(false);
         jLabel8.setVisible(false);
         jLabel3.setVisible(false);
         jLabel4.setVisible(false);
         
         jTextField6.setVisible(false);
         jTextField7.setVisible(false);
         
         
         
         jLabel1.setIcon(new javax.swing.ImageIcon());
         jLabel2.setIcon(new javax.swing.ImageIcon());
         
        jTextField1.setText("Oyuncu1");
        
        
        jTextField8.setVisible(true);
        jTextField9.setVisible(true);
        
        
        
        
        
            } 
            
            else
                jCheckBox1.setVisible(true);
        
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    public static void main2(String[] args) {
        ArrayList<Integer> list = new ArrayList<Integer>();
        for (int i=1; i<11; i++) {
            list.add(new Integer(i));
        }
        Collections.shuffle(list);
        for (int i=0; i<3; i++) {
            System.out.println(list.get(i));
        }
    }
   
    
    
    
    
    
    
    
    int i=0;
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //jButton3.setVisible(false);
        //jButton1.setVisible(false);
       // jLabel1.setVisible(false);
      
        
          
        //String[] konum = new String[50];
       /* konum[0]="../pokemonOyunu/src/pokemonoyunu/img/pikachu.jpg";
        konum[1]="../pokemonOyunu/src/pokemonoyunu/img/balbasaur.jpg";
        konum[2]="../pokemonOyunu/src/pokemonoyunu/img/Charmander.jpg";
        konum[3]="../pokemonOyunu/src/pokemonoyunu/img/Squirtle.jpg";
        konum[4]="../pokemonOyunu/src/pokemonoyunu/img/Zubat.jpg";
        konum[5]="../pokemonOyunu/src/pokemonoyunu/img/Psyduck.jpg";
        konum[6]="../pokemonOyunu/src/pokemonoyunu/img/Snorlax.jpg";
        konum[7]="../pokemonOyunu/src/pokemonoyunu/img/Butterfree.jpg";
        konum[8]="../pokemonOyunu/src/pokemonoyunu/img/Jigglypuff.jpg";
        konum[9]="../pokemonOyunu/src/pokemonoyunu/img/Meowth.jpg";
        */
        
        
        
        /*
        jLabel1.setIcon(new javax.swing.ImageIcon(konum[kartlarİnsan[i]]));
        jLabel2.setIcon(new javax.swing.ImageIcon(konum[kartlarBilgisayar[i]]));
        */
        if( jCheckBox3.isSelected() == true )
        {
        insanKart1.setVisible(true);
        insanKart2.setVisible(true);
        
        jLabel9.setVisible(true);
        jLabel10.setVisible(true);
        for(int i=3;i<5;i++){
            System.out.println("+"+denemem[i]);
            System.out.println("-"+denemem1[i]);
        }
            
        
        
        insanKart1.setIcon(new javax.swing.ImageIcon(konum[kartlarİnsan[3]]));
        insanKart2.setIcon(new javax.swing.ImageIcon(konum[kartlarİnsan[4]]));
        
        jLabel9.setIcon(new javax.swing.ImageIcon(konum[kartlarBilgisayar[3]]));
        jLabel10.setIcon(new javax.swing.ImageIcon(konum[kartlarBilgisayar[4]]));
        }
        
        else if( jCheckBox1.isSelected() == true )
        {
            jLabel5.setVisible(true);
            jLabel6.setVisible(true);
         jLabel5.setIcon(new javax.swing.ImageIcon(konum[kartlarİnsan[3]]));
         jLabel6.setIcon(new javax.swing.ImageIcon(konum[kartlarİnsan[4]]));
            
          jLabel7.setVisible(true);
            jLabel8.setVisible(true);
         jLabel7.setIcon(new javax.swing.ImageIcon(konum[kartlarBilgisayar[3]]));
         jLabel8.setIcon(new javax.swing.ImageIcon(konum[kartlarBilgisayar[4]]));
         jButton1.setVisible(true);
        }
        
        
        
        
        
        
        jButton2.setVisible(false);
        
        
          
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    
   
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void insanKart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insanKart1ActionPerformed
        // TODO add your handling code here:
        //
        KartBittiMi++;
        if(KartBittiMi < 4)
        {
        jLabel1.setIcon(new javax.swing.ImageIcon(konum[kartlarİnsan[0]]));
        jLabel2.setIcon(new javax.swing.ImageIcon(konum[kartlarBilgisayar[0]]));
        
        SonSkorPc+=BilgisayarPuan[0];
        SonSkorİnsan+=İnsanPuan[0];
         jTextField3.setText(Integer.toString(SonSkorPc));
         jTextField4.setText(Integer.toString(SonSkorİnsan));
         
         insanKart1.setVisible(false);
         if(kartlarBilgisayar[0]==denemem[0]){
             jLabel9.setVisible(false);
         }
         if(kartlarBilgisayar[0]==denemem[1]){
             jLabel10.setVisible(false);
         }
         if(kartlarBilgisayar[0]==denemem[2]){
             jLabel11.setVisible(false);
         }
         
         
        }
        
         if( KartBittiMi >= 4 )
         {
             
             jLabel1.setIcon(new javax.swing.ImageIcon(konum[kartlarİnsan[3]]));
            
             
            jLabel2.setIcon(new javax.swing.ImageIcon(konum[kartlarBilgisayar[3]]));
             SonSkorPc+=BilgisayarPuan[3];
             SonSkorİnsan+=İnsanPuan[3];
             jTextField3.setText(Integer.toString(SonSkorPc));
             jTextField4.setText(Integer.toString(SonSkorİnsan));
             insanKart1.setVisible(false);
             jLabel9.setVisible(false);
           
             
             
             
         }
        if( KartBittiMi==3)
        {
            jButton2.setVisible(true);
        }
        
     
        
        
     
    }//GEN-LAST:event_insanKart1ActionPerformed

    private void insanKart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insanKart2ActionPerformed
        // TODO add your handling code here:
        KartBittiMi++;
        if( KartBittiMi < 4 )
        {
        jLabel1.setIcon(new javax.swing.ImageIcon(konum[kartlarİnsan[1]]));
        jLabel2.setIcon(new javax.swing.ImageIcon(konum[kartlarBilgisayar[1]]));
        
        
        SonSkorPc+=BilgisayarPuan[1];
        SonSkorİnsan+=İnsanPuan[1];
        jTextField3.setText(Integer.toString(SonSkorPc));
        jTextField4.setText(Integer.toString(SonSkorİnsan));
        insanKart2.setVisible(false);
        
         if(kartlarBilgisayar[1]==denemem[0]){
             jLabel9.setVisible(false);
         }
         if(kartlarBilgisayar[1]==denemem[1]){
             jLabel10.setVisible(false);
         }
         if(kartlarBilgisayar[1]==denemem[2]){
             jLabel11.setVisible(false);
         }
        
        
        
        
        }
        System.out.println("Kart "+ KartBittiMi);
        
         if( KartBittiMi >=4 )
         {
            
             jLabel1.setIcon(new javax.swing.ImageIcon(konum[kartlarİnsan[4]]));
             jLabel2.setIcon(new javax.swing.ImageIcon(konum[kartlarBilgisayar[4]]));
             
             SonSkorPc+=BilgisayarPuan[4];
             SonSkorİnsan+=İnsanPuan[4];
             jTextField3.setText(Integer.toString(SonSkorPc));
             jTextField4.setText(Integer.toString(SonSkorİnsan));
             insanKart2.setVisible(false);
             jLabel10.setVisible(false);
        
             
             
         }
         
         if( KartBittiMi==3)
        {
            jButton2.setVisible(true);
        }
       
        //jButton2.setVisible(false);
        
    }//GEN-LAST:event_insanKart2ActionPerformed

    private void insanKart3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insanKart3ActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new javax.swing.ImageIcon(konum[kartlarİnsan[2]]));
        jLabel2.setIcon(new javax.swing.ImageIcon(konum[kartlarBilgisayar[2]]));
        SonSkorPc+=BilgisayarPuan[2];
        SonSkorİnsan+=İnsanPuan[2];
        jTextField3.setText(Integer.toString(SonSkorPc));
        jTextField4.setText(Integer.toString(SonSkorİnsan));
        insanKart3.setVisible(false);
       
          if(kartlarBilgisayar[2]==denemem[0]){
             jLabel9.setVisible(false);
         }
         if(kartlarBilgisayar[2]==denemem[1]){
             jLabel10.setVisible(false);
         }
         if(kartlarBilgisayar[2]==denemem[2]){
             jLabel11.setVisible(false);
         }
        
        
        
        
        KartBittiMi++;
         
        if( KartBittiMi==3)
        {
            jButton2.setVisible(true);
        }
        
    }//GEN-LAST:event_insanKart3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
       
        
          
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        
        List<pokemon> pokemonList = new ArrayList<pokemon>();
        pokemonList = pokemonList();
        int[] sayilar = new int[10];
        sayilar = rand();

        
          
            
            if( jCheckBox1.isSelected() == true )
            {
                
             jCheckBox3.setVisible(false);
                
                
                
                

            BilgisayarOyuncusu pc = new BilgisayarOyuncusu();
            pc.setOyuncuID(1);
            pc.setOyuncuAdi("mustafa");
            for (int i = 0; i < 3; i++) {
                pc.kartListesi[i] = sayilar[i];
                System.out.println(pc.kartListesi[i]);

            }
            //  System.out.println(pokemonList.get(pc.kartListesi[0]).getPokemonName() + ", " + pokemonList.get(pc.kartListesi[0]).getPokemonID());

            InsanOyuncusu insan = new InsanOyuncusu();
            insan.setOyuncuID(1);
            insan.setOyuncuAdi("ömer");
            for (int i = 3; i < 6; i++) {
                insan.kartListesi[i-3] = sayilar[i];
                System.out.println(insan.kartListesi[i-3]);

            }
           
            int insanSkor=0;
            int pcSkor=0;
           
            
         
         konum[0]="../pokemonOyunu/src/pokemonoyunu/img/pikachu.jpg";
        konum[1]="../pokemonOyunu/src/pokemonoyunu/img/balbasaur.jpg";
        konum[2]="../pokemonOyunu/src/pokemonoyunu/img/Charmander.jpg";
        konum[3]="../pokemonOyunu/src/pokemonoyunu/img/Squirtle.jpg";
        konum[4]="../pokemonOyunu/src/pokemonoyunu/img/Zubat.jpg";
        konum[5]="../pokemonOyunu/src/pokemonoyunu/img/Psyduck.jpg";
        konum[6]="../pokemonOyunu/src/pokemonoyunu/img/Snorlax.jpg";
        konum[7]="../pokemonOyunu/src/pokemonoyunu/img/Butterfree.jpg";
        konum[8]="../pokemonOyunu/src/pokemonoyunu/img/Jigglypuff.jpg";
        konum[9]="../pokemonOyunu/src/pokemonoyunu/img/Meowth.jpg";
         
         insanKart1.setVisible(false);
         insanKart2.setVisible(false);
         insanKart3.setVisible(false);
         
         jLabel5.setIcon(new javax.swing.ImageIcon(konum[insan.kartListesi[0]]));
         jLabel6.setIcon(new javax.swing.ImageIcon(konum[insan.kartListesi[1]]));
         jLabel3.setIcon(new javax.swing.ImageIcon(konum[insan.kartListesi[2]]));
         
         jLabel7.setIcon(new javax.swing.ImageIcon(konum[pc.kartListesi[0]]));
         jLabel8.setIcon(new javax.swing.ImageIcon(konum[pc.kartListesi[1]]));
         jLabel4.setIcon(new javax.swing.ImageIcon(konum[pc.kartListesi[2]]));
            
             int tut=0;
            int tut1=0;
            System.arraycopy(pc.kartListesi,0,denemem,0,5);
            System.arraycopy(insan.kartListesi,0,denemem1,0,5);
            for(int i=0;i<3;i++){
                for(int j=i;j<3;j++){
                    if(pc.kartListesi[i]<pc.kartListesi[i+1]){
                    tut=pc.kartListesi[i];
                    pc.kartListesi[i]=pc.kartListesi[i+1];
                    pc.kartListesi[i+1]=tut;
                    }
                    if(insan.kartListesi[i]<insan.kartListesi[i+1]){
                       tut1= insan.kartListesi[i];
                       insan.kartListesi[i]=insan.kartListesi[i+1];
                       insan.kartListesi[i+1]=tut1;
                    }
                    
                }
            }
            
            

            for(int i=0;i<3;i++)
            {
                System.out.println(pokemonList.get(pc.kartListesi[i]).hasarPuaniGoster()+"    "+pokemonList.get(insan.kartListesi[i]).hasarPuaniGoster());
                if(pokemonList.get(pc.kartListesi[i]).hasarPuaniGoster()>pokemonList.get(insan.kartListesi[i]).hasarPuaniGoster()){
                    //pcSkor=pcSkor+5;
                    pcSkor=5;
                    insanSkor=0;
                    İnsanPuan[i]=insanSkor;
                    BilgisayarPuan[i]=pcSkor;
                    System.out.println("1.puan "+pcSkor);
                    System.out.println("2.puan "+insanSkor);
                  
                }
                else if (pokemonList.get(pc.kartListesi[i]).hasarPuaniGoster()<pokemonList.get(insan.kartListesi[i]).hasarPuaniGoster()){
                    //insanSkor=insanSkor+5;
                    pcSkor=0;
                    insanSkor=5;
                    İnsanPuan[i]=insanSkor;
                    System.out.println("1.puan "+pcSkor);
                    System.out.println("2.puan "+insanSkor);
                    BilgisayarPuan[i]=pcSkor;
                }
                else {
                    insanSkor=insanSkor+0;
                    //pcSkor=pcSkor+0;
                    pcSkor=0;
                    insanSkor=0;
                    İnsanPuan[i]=insanSkor;
                    System.out.println("1.puan "+pcSkor);
                    System.out.println("2.puan "+insanSkor);
                    BilgisayarPuan[i]=pcSkor;

                }
            }
            
            
            
            insan.kartListesi[3]=sayilar[6];
            pc.kartListesi[3]=sayilar[7];
            insan.kartListesi[4]=sayilar[8];
            pc.kartListesi[4]=sayilar[9];
            
            for(int i=3;i<5;i++){
                System.out.println(pokemonList.get(pc.kartListesi[i]).hasarPuaniGoster()+"    "+pokemonList.get(insan.kartListesi[i]).hasarPuaniGoster());
                if(pokemonList.get(pc.kartListesi[i]).hasarPuaniGoster()>pokemonList.get(insan.kartListesi[i]).hasarPuaniGoster()){
                    pcSkor=5;
                    insanSkor=0;
                    İnsanPuan[i]=insanSkor;
                    BilgisayarPuan[i]=pcSkor;
                    
                    System.out.println("1.puan: "+pcSkor);
                    System.out.println("2.puan: "+insanSkor);
                }
                else if(pokemonList.get(pc.kartListesi[i]).hasarPuaniGoster()<pokemonList.get(insan.kartListesi[i]).hasarPuaniGoster()){
                    insanSkor=5;
                    İnsanPuan[i]=insanSkor;
                    pcSkor=0;
                    BilgisayarPuan[i]=pcSkor;
                    System.out.println("1.puan: "+pcSkor);
                    System.out.println("2.puan: "+insanSkor);

                }
                else{
                    pcSkor=0;
                    BilgisayarPuan[i]=pcSkor;
                    insanSkor=0;
                    İnsanPuan[i]=insanSkor;
                    System.out.println("1.puan: "+pcSkor);
                    System.out.println("2.puan: "+insanSkor);

                }

            }
            if(pcSkor>insanSkor){
                System.out.println("1.oyuncu bilgisayaar kazandi");
            }
            else if(insanSkor>pcSkor)
            {
                System.out.println("2.oyuncu insan kazandi");
            }
            else{
                System.out.println("berabere kaldiniz");
            }
            
            

         for(int i=0; i<5 ; i++)
         {
             kartlarİnsan[i]=insan.kartListesi[i];
             kartlarBilgisayar[i]=pc.kartListesi[i];
         }
         
         
         
         jButton2.setVisible(false);
         
         
         jLabel5.setVisible(true);
         jLabel7.setVisible(true);
         jLabel6.setVisible(true);
         jLabel8.setVisible(true);
         jLabel3.setVisible(true);
         jLabel4.setVisible(true);
         
         jButton1.setVisible(true);
         
         
         jLabel1.setIcon(new javax.swing.ImageIcon());
         jLabel2.setIcon(new javax.swing.ImageIcon());
         
         Sayac=0;
         
          jTextField1.setText("Bilgisayar1");
          
          
          SonSkorPc=0;
        jTextField3.setText(Integer.toString(SonSkorPc));
        SonSkorİnsan=0;
        jTextField4.setText(Integer.toString(SonSkorİnsan));
        
        jTextField6.setVisible(true);
        jTextField7.setVisible(true);
        
        
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        
        
        jTextField8.setVisible(false);
        jTextField9.setVisible(false);
        
         
         
         
        
            }
            else
                jCheckBox3.setVisible(true);
            
            
            
            
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(Sayac==0)
        {
            
            if(kartlarİnsan[0]==denemem1[0]){
                jLabel5.setVisible(false);                
            }
            if(kartlarİnsan[0]==denemem1[1]){
                jLabel6.setVisible(false);                
            }
            if(kartlarİnsan[0]==denemem1[2]){
                jLabel3.setVisible(false);                
            }
            if(kartlarBilgisayar[0]==denemem[0]){
                jLabel7.setVisible(false);                
            }
            if(kartlarBilgisayar[0]==denemem[1]){
                jLabel8.setVisible(false);                
            }
            if(kartlarBilgisayar[0]==denemem[2]){
                jLabel4.setVisible(false);                
            }
       
        jLabel1.setIcon(new javax.swing.ImageIcon(konum[kartlarİnsan[0]]));
        jLabel2.setIcon(new javax.swing.ImageIcon(konum[kartlarBilgisayar[0]]));
        SonSkorPc+=BilgisayarPuan[0];
        SonSkorİnsan+=İnsanPuan[0];
        
        
        }
        
        if(Sayac==1)
        {
       
             if(kartlarİnsan[1]==denemem1[0]){
                jLabel5.setVisible(false);                
            }
            if(kartlarİnsan[1]==denemem1[1]){
                jLabel6.setVisible(false);                
            }
            if(kartlarİnsan[1]==denemem1[2]){
                jLabel3.setVisible(false);                
            }
            if(kartlarBilgisayar[1]==denemem[0]){
                jLabel7.setVisible(false);                
            }
            if(kartlarBilgisayar[1]==denemem[1]){
                jLabel8.setVisible(false);                
            }
            if(kartlarBilgisayar[1]==denemem[2]){
                jLabel4.setVisible(false);                
            }
            
            
        jLabel1.setIcon(new javax.swing.ImageIcon(konum[kartlarİnsan[1]]));
        jLabel2.setIcon(new javax.swing.ImageIcon(konum[kartlarBilgisayar[1]]));
        SonSkorPc+=BilgisayarPuan[1];
        SonSkorİnsan+=İnsanPuan[1];
        
        }
        
        if(Sayac==2)
        {
       
             if(kartlarİnsan[2]==denemem1[0]){
                jLabel5.setVisible(false);                
            }
            if(kartlarİnsan[2]==denemem1[1]){
                jLabel6.setVisible(false);                
            }
            if(kartlarİnsan[2]==denemem1[2]){
                jLabel3.setVisible(false);                
            }
            if(kartlarBilgisayar[2]==denemem[0]){
                jLabel7.setVisible(false);                
            }
            if(kartlarBilgisayar[2]==denemem[1]){
                jLabel8.setVisible(false);                
            }
            if(kartlarBilgisayar[2]==denemem[2]){
                jLabel4.setVisible(false);                
            }
            
            
        jButton2.setVisible(true);
           jButton1.setVisible(false);
        jLabel1.setIcon(new javax.swing.ImageIcon(konum[kartlarİnsan[2]]));
        jLabel2.setIcon(new javax.swing.ImageIcon(konum[kartlarBilgisayar[2]]));
        SonSkorPc+=BilgisayarPuan[2];
        SonSkorİnsan+=İnsanPuan[2];
        }
        
        if(Sayac==3)
        {
           
           jLabel5.setVisible(false);
           jLabel7.setVisible(false);
           jLabel1.setIcon(new javax.swing.ImageIcon(konum[kartlarİnsan[3]]));
           jLabel2.setIcon(new javax.swing.ImageIcon(konum[kartlarBilgisayar[3]]));
           SonSkorPc+=BilgisayarPuan[3];
           SonSkorİnsan+=İnsanPuan[3];
           
        }
        
        if(Sayac==4)
        {
           jButton2.setVisible(false);
           jLabel6.setVisible(false);
           jLabel8.setVisible(false);
           jLabel1.setIcon(new javax.swing.ImageIcon(konum[kartlarİnsan[4]]));
           jLabel2.setIcon(new javax.swing.ImageIcon(konum[kartlarBilgisayar[4]]));
           SonSkorPc+=BilgisayarPuan[4];
           SonSkorİnsan+=İnsanPuan[4];
           
        }
        
        
        
        
        jTextField3.setText(Integer.toString(SonSkorPc));
        jTextField4.setText(Integer.toString(SonSkorİnsan));
        
        
        
        
        
        
        Sayac++;
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
   

    
    
    
    
    
    
    
    
    public static List pokemonList() {
        List<pokemon> pokemonList = new ArrayList<pokemon>();

        Pikachu pikachu = new Pikachu();
        pikachu.setPokemonID(0);
        pikachu.setPokemonName("pikachu");
        pikachu.setTip("Elektrik");
        pikachu.hasarPuani = 40;

        pokemonList.add(pikachu);

        // System.out.println(pokemonList.get(0).getPokemonName() + ", " + pokemonList.get(0).getPokemonID());
   
        Bulbasaur bulbasaur = new Bulbasaur();
        bulbasaur.setPokemonID(1);
        bulbasaur.setPokemonName("Bulbasaur");
        bulbasaur.setTip("Çim");
        bulbasaur.hasarPuani = 50;
        pokemonList.add(bulbasaur);
        //int hasar_puani = pokemonList.get(1).hasarPuaniGoster();
        //System.out.println("dfghjklşişlkjhgfdsdfghm   "+hasar_puani);
        Charmander charmander = new Charmander();
        charmander.setPokemonID(2);
        charmander.setPokemonName("charmander");
        charmander.setTip("Ateş");
        charmander.hasarPuani = 60;
        pokemonList.add(charmander);

        Squirtle squirtle = new Squirtle();
        squirtle.setPokemonID(3);
        squirtle.setPokemonName("squirtle");
        squirtle.setTip("Su");
        squirtle.hasarPuani = 30;

        pokemonList.add(squirtle);

        Zubat zubat = new Zubat();
        zubat.setPokemonID(4);
        zubat.setPokemonName("zubat");
        zubat.setTip("Hava");
        zubat.hasarPuani = 50;
        pokemonList.add(zubat);

        Psyduck psyduck = new Psyduck();
        psyduck.setPokemonID(5);
        psyduck.setPokemonName("psyduck");
        psyduck.setTip("Su");
        psyduck.hasarPuani = 20;
        pokemonList.add(psyduck);

        Snorlax snorlax = new Snorlax();
        snorlax.setPokemonID(6);
        snorlax.setPokemonName("snorlax");
        snorlax.setTip("Normal");
        snorlax.hasarPuani = 30;

        pokemonList.add(snorlax);

        Butterfree butterfree = new Butterfree();
        butterfree.setPokemonID(7);
        butterfree.setPokemonName("butterfree");
        butterfree.setTip("Hava");
        butterfree.hasarPuani = 10;
        pokemonList.add(butterfree);

        Jigglypuff jigglypuff = new Jigglypuff();
        jigglypuff.setPokemonID(8);
        jigglypuff.setPokemonName("jigglypuff");
        jigglypuff.setTip("Ses");
        jigglypuff.hasarPuani = 70;
        pokemonList.add(jigglypuff);

        Meowth meowth = new Meowth();
        meowth.setPokemonID(9);
        meowth.setPokemonName("meowth");
        meowth.setTip("Normal");
        meowth.hasarPuani = 40;
        pokemonList.add(meowth);

        return pokemonList;
    }

    public static int[] rand() {
        Random rnd = new Random();

        int RastgeleSayi;
        RastgeleSayi = (int) (Math.random() * 10) ;
        int[] sayilar = new int[10];
        sayilar[0] = RastgeleSayi;
        for (int i = 1; i < sayilar.length; i++) {
            RastgeleSayi = (int) (Math.random() * 10) ;
            for (int j = 0; j < i; j++) {
                if (sayilar[j] == RastgeleSayi) {
                    i--;
                    break;
                } else {
                    sayilar[i] = RastgeleSayi;
                }
            }
        }
        for (int i = 0; i < sayilar.length; i++) {
            //    System.out.println(sayilar[i]);
        }

        return sayilar;
    }

    public static void main(String args[]) {    
        
            /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokemonOyunu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokemonOyunu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokemonOyunu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokemonOyunu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        PokemonOyunu1 a = new PokemonOyunu1();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PokemonOyunu1().setVisible(true);
                int secim = 0;
              
                
                
            }
        });
    }
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton insanKart1;
    private javax.swing.JButton insanKart2;
    private javax.swing.JButton insanKart3;
    private javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    public static javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    

}
